// <auto-generated />
namespace Kaid.WebAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class change_key_for_IdentityUserRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_key_for_IdentityUserRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201905190809303_change_key_for_IdentityUserRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
